[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:04:45.442 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:09:45.453 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:17.306 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3f010b12 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:22.312 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@740b6c6d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:27.322 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3e91c2ef (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:32.332 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@9ff17b4 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:37.385 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1f3a514d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:42.399 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2f8c7eff (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:11:47.003 [DiscoveryClient-HeartbeatExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:11:47.003 [DiscoveryClient-CacheRefreshExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#?:? -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:47.414 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3b359042 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:52.428 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3a7fedf0 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:11:57.432 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@f326784 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:13:15.144 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:14:47.141 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:18:16.831 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:19:47.142 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:23:16.842 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:24:47.154 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:28:16.848 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:29:35.077 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4bde304b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:29:40.081 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@598be03f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:29:45.082 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@783cb895 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:29:47.155 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.275 [SpringApplicationShutdownHook] INFO  org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry#deregister:62 -Unregistering application VM-SERVICE with eureka with status DOWN
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.276 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Saw local status change event StatusChangeEvent [timestamp=1753363873276, current=DOWN, previous=UP]
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.279 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@1a4ccb7b{STOPPING}[11.0.15,sto=0]
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.283 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@3cb1a148{HTTP/1.1, (http/1.1)}{0.0.0.0:9911}
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.284 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#?:? -Destroying Spring FrameworkServlet 'dispatcherServletRegistration'
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.285 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@44971269{application,/,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9911.13185224707170232777/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.288 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service paused.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.288 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@2b66bf1c{STOPPING}[11.0.15,sto=0]
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.290 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@4b5f022f{HTTP/1.1, (http/1.1)}{0.0.0.0:9011}
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.291 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#?:? -Destroying Spring FrameworkServlet 'dispatcherServlet'
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.292 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@3cd6d147{application,/vm-service,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9011.11937668215530286101/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.299 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown initiated...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.302 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown completed.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.302 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@100ba3d7 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.305 [SpringApplicationShutdownHook] INFO  org.springframework.scheduling.quartz.SchedulerFactoryBean#?:? -Shutting down Quartz Scheduler
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.305 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutting down.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.305 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#standby:585 -Scheduler vm-service_$_vm-service paused.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.305 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutdown complete.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.306 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown initiated...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.306 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.308 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown initiated...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.309 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:13.348 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Shutting down DiscoveryClient ...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.362 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Unregistering ...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.359 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:906)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:164)
	... 24 common frames omitted
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.377 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.379 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.387 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.cloud.health.RefreshScopeHealthIndicator#logExceptionIfPresent:94 -Health check failed
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:2056)
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:48)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.394 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.netflix.discovery.DiscoveryClient#?:? -Exception from healthcheckHandler.getStatus, setting status to DOWN
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1710)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:173)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:150)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	... 14 common frames omitted
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.394 [DiscoveryClient-InstanceInfoReplicator-0] INFO  com.netflix.discovery.DiscoveryClient#register:817 -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011: registering service...
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.418 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011 - deregister  status: 200
[11220] [application.name_IS_UNDEFINED] 2025-07-24 21:31:16.433 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Completed shut down of DiscoveryClient
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:33:16.859 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:38:16.873 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:40:42.674 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4b8fca40 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:40:47.678 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@45fa1b18 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:40:52.690 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@90a12a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:40:57.693 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@664dadea (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:41:02.745 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@76663e54 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:41:07.748 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@314db0c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:41:12.756 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@65dba04d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:41:17.762 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@20473b9d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:41:22.776 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@475e4fdd (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:43:16.879 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:48:16.884 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:53:10.499 [DiscoveryClient-HeartbeatExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#?:? -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:53:16.891 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.642 [SpringApplicationShutdownHook] INFO  org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry#deregister:62 -Unregistering application VM-SERVICE with eureka with status DOWN
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.642 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Saw local status change event StatusChangeEvent [timestamp=1753365444642, current=DOWN, previous=UP]
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.645 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@4c601487{STOPPING}[11.0.15,sto=0]
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.647 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@65a03e98{HTTP/1.1, (http/1.1)}{0.0.0.0:9911}
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.647 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#?:? -Destroying Spring FrameworkServlet 'dispatcherServletRegistration'
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.648 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@44cea6bb{application,/,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9911.11585188494069747051/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.652 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service paused.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.652 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@9fc2f89{STOPPING}[11.0.15,sto=0]
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.655 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@61b76a7d{HTTP/1.1, (http/1.1)}{0.0.0.0:9011}
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.656 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#log:2355 -Destroying Spring FrameworkServlet 'dispatcherServlet'
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.656 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@797ee1a9{application,/vm-service,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9011.10514380852861847484/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.663 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown initiated...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.669 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown completed.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  org.springframework.scheduling.quartz.SchedulerFactoryBean#?:? -Shutting down Quartz Scheduler
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutting down.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service paused.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7fbfd6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutdown complete.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown initiated...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.673 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.674 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-2 - Shutdown initiated...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.674 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-2 - Shutdown completed.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.676 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#close:350 -DatebookHikariCP - Shutdown initiated...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.677 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:24.714 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Shutting down DiscoveryClient ...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.730 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Unregistering ...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.729 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:906)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:164)
	... 24 common frames omitted
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.732 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.732 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.733 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.735 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.cloud.health.RefreshScopeHealthIndicator#?:? -Health check failed
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:2056)
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:48)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.739 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.netflix.discovery.DiscoveryClient#?:? -Exception from healthcheckHandler.getStatus, setting status to DOWN
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1710)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:173)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:150)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	... 14 common frames omitted
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.739 [DiscoveryClient-InstanceInfoReplicator-0] INFO  com.netflix.discovery.DiscoveryClient#?:? -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011: registering service...
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.772 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011 - deregister  status: 200
[37108] [application.name_IS_UNDEFINED] 2025-07-24 21:57:27.782 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Completed shut down of DiscoveryClient
[22696] [application.name_IS_UNDEFINED] 2025-07-24 21:58:16.907 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:03:16.921 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:08:16.934 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:06.849 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@638e558 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:11.861 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4aa631b2 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:16.869 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7e23780f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:21.879 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4420cd4b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:26.883 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@51e38a02 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:31.995 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@9ade0fb (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:37.005 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@65b1efc (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:42.007 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@193899ed (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:10:47.018 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7f741809 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[22696] [application.name_IS_UNDEFINED] 2025-07-24 22:13:16.952 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
